POST http://localhost:9000/sendMail HTTP/1.1
Content-Type: application/json

{
  "cucumber": 146
}

###
GET http://localhost:9000/sendMail HTTP/1.1

###
POST http://localhost:9000/parsePrice HTTP/1.1
Content-Type: application/json

{
  "classFrom": "qiwi"
}